server:
  port: 0  # Client can choose any available port if needed

some:
  message: "This is inventory service config from config server"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: root123
